### ISSUE TITLE
Use consistent representation of Stackdriver variables

### ISSUE THREAD

**Issue by eyqs** [GoogleCloudPlatform/cloud-debug-proxy-chrome-devtools#1]
This repo currently relies on manually parsing the string in the `value` property of [Stackdriver variables](https://cloud.google.com/debugger/api/reference/rest/v2/debugger.debuggees.breakpoints#Variable). This variable is created in the [debug agent](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/), which currently does not offer a consistent representation; it returns completely different things on Node 8 and Node 10.

The code in [`parseVariable`](https://github.com/GoogleCloudPlatform/cloud-debug-proxy-common/blob/master/src/adapter.ts) should be replaced with code that uses this consistent representation once it is created. The issue tracking its creation in the debug agent is [#504](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/504).

**Comment by ofrobots** [comment]
We decided to use a different code path for IDE integration.
